ebnf = { rule }>0 ;
rule = identifier , ' = ' , alternation , " ;\n" ;
identifier = letter , { word } ;
letter = 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i'
       | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r'
       | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z'
       | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I'
       | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R'
       | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z' ;
digit = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' ;
word = letter/10 | digit/5 | '_' | ' ' ;
alternation = concatenation, { ' | ', alternation }%25 ;
concatenation = atom, { ' , ', concatenation }%25 ;
atom = ( '[ ', alternation, ' ]' )
     | ( '( ', alternation, ' )' )
     | ( '{ ', alternation, ' }' )
     | identifier/5
     | terminal/20 ;
terminal = "'" , { word }>0<5 , "'" ;
