expression = '(' , id , { ' ' , argument }%75<4 , ')' ;

word = 'a'/3 | 'b' | 'c' | 'd' | 'e'/3 | 'f' | 'g' | 'h' | 'i'/3
     | 'j' | 'k' | 'l' | 'm' | 'n' | 'o'/3 | 'p' | 'q' | 'r'
     | 's'/7 | 't' | 'u'/3 | 'v' | 'w' | 'x' | 'y' | 'z' ;

digit = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' ;

any letter = word/10 | digit/5 | ' '/2 ;

id = { word }>0<6 ;

argument = string
         | number
         | expression ;

string = '"' , { any letter }>0 , '"' ;

number = { digit }>0 , [ '.' , { digit }>0 ] ;
